name: Dev - Mobileapp Tests CI
on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]
jobs:
  trigger_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.MOBILEAPP_REPO_ACCESS_TOKEN }}
        repository: foundationmsf/mobileapp
        event-type: improc-dev-tests